### ISSUE TITLE
Tab icons for more processes

### ISSUE THREAD

**Issue by henrikruscon** [henrikdahl/hyper-tabs-enhanced#1]
Let me know if you want tab icons for more processes. I'll simply create and add them ✌️

**Comment by KarlHerler** [comment]
One (hopefully) quick addition would be to add [nvim](https://neovim.io/) to use the same icon as vim. Would at least make my life a bit happier as prefer neovim.

**Comment by henrikruscon** [comment]
@KarlHerler is the process name `neovim` or `nvim`? ✌️

**Comment by KarlHerler** [comment]
It's `nvim` :+1:

**Comment by henrikruscon** [comment]
I just pushed a version that supports `nvim`

**Comment by KarlHerler** [comment]
Great, Tackar :1st_place_medal:! Pulled it and works like a charm!

![2017-01-17-222002_1434x75_scrot](https://cloud.githubusercontent.com/assets/209866/22038288/354b339c-dd03-11e6-870f-a875703b8226.png)

**Comment by xeroxoid** [comment]
How about grunt, yarn, npm, mongo and redis? :P

**Comment by henrikruscon** [comment]
@xeroxoid There is yarn & npm. I'll make sure to add the rest you mentioned ✌️
