### ISSUE TITLE
Tab background remains black

### ISSUE THREAD

**Issue by weedgrease** [henrikdahl/hyper-tabs-enhanced#10]
Hey there!
Thanks for your awesome work - I'm currently having an issue since installing your plugin where the background of inactive tabs are black:

![image](https://cloud.githubusercontent.com/assets/10536167/23568770/17d9cb12-002a-11e7-8305-c4a135ff28e0.png)

Here's my current [config](https://gist.github.com/kevingelion/cd0a3e35ef10aa6c48432ccc90736082)

Here's the CSS for the tab (I'm guessing this is a class built-in to hyper?):  
```
.tab_tab {
    color: hsl(0, 0%, 36%);
    border-color: transparent !important;
    background-color: hsl(0, 0%, 0%);
    transition: background 150ms ease;
}
```

**Comment by henrikruscon** [comment]
@kevingelion 

Thanks for your kind works ✌️

Problem is that the theme is specified after `hyper-statusline` and `hyper-tabs-enhanced` in your config. Both plugins fetch your current themes colors but at the point they are loaded your only active theme is the default one. So it ends up fetching Hyper's default black color.

Example solution:
 ```javascript
 plugins: [
    "hyper-chesterish",
    "hyper-statusline",
    "hyper-tabs-enhanced",
  ],
```

**Comment by weedgrease** [comment]
Ah, okay that fixed it! Sorry, I didn't know the order of the array mattered, but it makes sense that it does now that I think about it. Thanks!
