### ISSUE TITLE
Plugin & Config

### ISSUE THREAD

**Issue by ghughes27** [henrikdahl/hyper-tabs-enhanced#11]
Thanks for the plugin! It might be just me but I can't get the plugin to work. I have the hyper-chesterish and -statusline plugins installed. Oddly the ~/.hyper.js config cmd doesn't seem to be working properly either which may be the root of the problem...  Running it on Windows 10 through git-cmd.exe shell with shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],

![hyper](https://cloud.githubusercontent.com/assets/18358509/23726550/9fad70f6-0422-11e7-83e4-1f5fa3b6857e.PNG)

**Comment by henrikruscon** [comment]
Thanks for you support! ✌️

There was an issue with Hyper causing plugins to fail which has been fixed in Hyper 1.3.0 that was just released. It might be related to your issue.
