### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ymatuhin** [henrikdahl/hyper-tabs-enhanced#12]
Hi. I'm very sorry for interrupting you.I have maybe a stupid question, but I cant find the answer. 
In your screenshots (in tabs) I see after ⚡ character only `~`. But I have whole username — https://monosnap.com/file/FkOqrmNgl99n2H898CZZi6G8bAsfaF. Can you help me hide this?

**Comment by henrikruscon** [comment]
It has to do with your shell. I suggest you check out https://github.com/sindresorhus/pure

**Comment by ymatuhin** [comment]
I have already installed the pure with oh-my-zsh and have no idea why I see the full name instead of short `~`. Anyway thank you.

**Comment by henrikruscon** [comment]
Closing since it's unrelated to `hyper-tabs-enhanced`. Hope you got it solved ✌️
