### ISSUE TITLE
Align Close Button Right

### ISSUE THREAD

**Issue by Joshua-Cummings** [henrikdahl/hyper-tabs-enhanced#16]
Is there currently any way to set the close icon to the right side of tabs?

**Comment by henrikruscon** [comment]
Sorry for the delayed response!

I could add this as an option if you still want this feature? ✌️

**Comment by henrikruscon** [comment]
I've added a config option to align the close button to left/right in the latest commit (v0.4.1).

I've also added it doc to the readme ✌️
