### ISSUE TITLE
Broken on macOS High Sierra

### ISSUE THREAD

**Issue by NetOpWibby** [henrikdahl/hyper-tabs-enhanced#22]
I'm assuming Apple changed some APIs because all I see is the default window bar and it's covering my tabs.

**Comment by ELLIOTTCABLE** [comment]
Screenshot, for reference:

![screen shot 2017-06-06 at 09 07 30](https://cloud.githubusercontent.com/assets/200/26833274/99453904-4a97-11e7-9b16-8a4792164556.png)

**Comment by henrikruscon** [comment]
I'll have to install macOS High Sierra to debug this. Thanks for letting me know ✌️

**Comment by henrikruscon** [comment]
Is this still an issue? Seems to be an issue with electron itself [#9753](https://github.com/electron/electron/issues/9753)

**Comment by NetOpWibby** [comment]
Oh that's beautiful, the issue's been fixed.
