### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by nikolajnyboe** [henrikdahl/hyper-tabs-enhanced#23]
When I try to config the plug-in the get an error when saving hyper.js

<img width="445" alt="skaermbillede 2017-07-05 kl 22 11 17" src="https://user-images.githubusercontent.com/16170841/27885913-0e9d4dd2-61da-11e7-93ff-b35456e120a3.png">

I have placed the override rule here:

<img width="277" alt="skaermbillede 2017-07-05 kl 23 32 00" src="https://user-images.githubusercontent.com/16170841/27885968-4b87193a-61da-11e7-93b5-5deb8879b735.png">

Am I doing it wrong? :)

**Comment by lukasmalkmus** [comment]
Missing `,` behind the closing bracket `}`?

**Comment by henrikruscon** [comment]
You've placed it in the proper place but like @lukasmalkmus pointed out, you're missing a comma. ✌️ 

```javascript
hyperTabs: {
  trafficButtons: true,
},

fontSize: 12,
```

**Comment by nikolajnyboe** [comment]
Thanks!
