### ISSUE TITLE
Add support to keep default window controls

### ISSUE THREAD

**Issue by jcarrillo7** [henrikdahl/hyper-tabs-enhanced#4]
It would be nice if this plugin would only affect the tab style / icons and would not replace the window close/minimize/hide buttons (Mac).

**Comment by henrikruscon** [comment]
I've been planning to implement this as an option but I've lacked time. I'll look at it soon but feel free to PR it if you want it right now ✌️

**Comment by henrikruscon** [comment]
Just pushed a version that includes custom traffic buttons that can be enabled by config, default is `false`

How to enable it is written in readme. Let me know if that works for you @jcarrillo7 ✌️

**Comment by jcarrillo7** [comment]
@henrikdahl awesome thanks! I did notice a small inconsistency where the traffic buttons are still grayed out when the window is in focus. The behavior is normally to have color when in focus and not just when you hover over them.

**Comment by henrikruscon** [comment]
@jcarrillo7 yeah that was an artistic choice because I personally think it looks better blended in.

Would you prefer if it had the default behavior you described? ✌️

**Comment by jcarrillo7** [comment]
@henrikdahl personally yes so it fits with the rest of macOS. But I understand if you want to keep it how it is.

**Comment by jcarrillo7** [comment]
@henrikdahl Also noticed the traffic icons don't show their symbol when hovered over?

http://www.iostipsandtricks.biz/images/20150507/20150507000015-smhlainyjyz.png

**Comment by henrikruscon** [comment]
@jcarrillo7 also intentional for a cleaner look, traffic buttons also lack borders if you compare them to original for a flat appearence ✌️

I'll consider adding an option to pick between custom and default traffic lights.

**Comment by jcarrillo7** [comment]
@henrikdahl ah yeah that option would be great. The current implementation leads to behavior differences Mainly that the "green" button is supposed to full screen the app on OS X and only maximize it when option is held down.

**Comment by henrikruscon** [comment]
@jcarrillo7 Not sure if you're still using this but I've decided to replace the custom traffic buttons with native ones. The configuration remains the same ✌️ 

Pushing the commit now
