### ISSUE TITLE
Align Close Button Right configuration is not working

### ISSUE THREAD

**Issue by ketozhang** [henrikdahl/hyper-tabs-enhanced#42]
Using Hyper 2.1.2 on Windows 10 (for WSL). 

The close button still stays on the left after setting `closeAlign: 'right'`. See screenshot

![image](https://user-images.githubusercontent.com/13506487/53688282-ac30a000-3cf6-11e9-8a4b-343a72de3df9.png)

**Comment by jkmartindale** [comment]
Be sure to place your `hyperTabs:{}` config before the closing curly brace of `config:{}`, which comes before `plugins:[]`.
