### ISSUE TITLE
[Icon] Fish shell

### ISSUE THREAD

**Issue by pinage404** [henrikdahl/hyper-tabs-enhanced#44]
Hi,

Can you add an icon for [Fish](https://fishshell.com/) please ?

Maybe the logo of [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish) ?

![Oh My Fish's logo](https://cdn.rawgit.com/oh-my-fish/oh-my-fish/e4f1c2e0219a17e2c748b824004c8d0b38055c16/docs/logo.svg)

**Comment by asbarron** [comment]
I think this repo is dead.
