### ISSUE TITLE
Icons on tab are not appearing

### ISSUE THREAD

**Issue by possebon** [henrikdahl/hyper-tabs-enhanced#5]
I'm running the Hyper.js 1.1.0.1408 on macOS Sierra. The icons does not appears as process running.

This is my .hyper.js file:
[https://gist.github.com/anonymous/13c4f0a3c054b5d183d123bd1fb27998](url)

![image](https://cloud.githubusercontent.com/assets/257745/22957138/8548e1c6-f30d-11e6-9f73-ff0532c10cd8.png)

**Comment by henrikruscon** [comment]
There's currently no process icon for python. What processes are you using? I'll add support for them ✌️

**Comment by henrikruscon** [comment]
In the screenshot it looks like you're loading `hyper-tabs-enhanced` before the theme, if you run it after the theme, it'll take the colors from that theme instead of default Hyper theme.

For example:

```javascript
  plugins: [
    'hyper-chesterish',
    'hyper-tabs-enhanced',
    'hyper-statusline',
  ],
```

**Comment by possebon** [comment]
Basically, Python, mySQL, vim.

Awesome plugin, congratulations.

I tested another tab-icon [https://github.com/dfrankland/hyper-tab-icons](url), but yours is more complete.

You could take a look on other plugin (above) to get inspiration of what icons you could add support.

Best regards,

Fernando Possebon

**Comment by henrikruscon** [comment]
Thanks! 👊

Just added support for Python & MySQL, it already supported Vim. Let me know if it works for you ✌️

**Comment by henrikruscon** [comment]
@possebon Is this solved?

**Comment by possebon** [comment]
@henrikdahl I'll test tonight at my macOS. This should work anyway on Linux, right? I tested now, and still does not show on Python

![image](https://cloud.githubusercontent.com/assets/257745/23036329/8b9be7f0-f469-11e6-91da-d2fbe5083a59.png)

This is a new install of plugin, so I'm sure that is the latest version. On macOS I need to update it, right?

**Comment by henrikruscon** [comment]
@possebon Only reliable way to get current running process is through the title, since your linux shell doesn't appear to include python in your title, it won't work.

**Comment by possebon** [comment]
Humm... I'll take a look on how to do it. I installed no the oh-my-zsh but still does not show the process name on title.

Thanks anyway for your attention @henrikdahl

**Comment by possebon** [comment]
@henrikdahl I gotta working the process name on title

![image](https://cloud.githubusercontent.com/assets/257745/23038135/0ed48ee6-f470-11e6-8d5f-8c8e9eb80ddc.png)

But still not working the icon. Maybe is not considering case insensitive?

**Comment by henrikruscon** [comment]
@possebon It appears its not showing any icon? Seems the issue is something else now, it should always show the default one. Can you inspect the HTML to see what's there?

**Comment by possebon** [comment]
@henrikdahl Do you want I check something in particular? 

I'm now with macOS, the same situation, and this is the screen with Developer Tools

![image](https://cloud.githubusercontent.com/assets/257745/23064736/ef466c96-f4f8-11e6-8080-ea9a72b3e411.png)

**Comment by henrikruscon** [comment]
@possebon Do you get an icon if you run php for example?

**Comment by possebon** [comment]
Yes, it works.

![image](https://cloud.githubusercontent.com/assets/257745/23067384/35e23d76-f506-11e6-978b-645c057c1697.png)

**Comment by henrikruscon** [comment]
@possebon That means you're not running the latest version. Comment out `hyper-tabs-enhanced` and reload plugins, then comment it back in and restart Hyper to make sure it's running the latest.

<img width="533" alt="skarmavbild 2017-02-17 kl 14 55 13" src="https://cloud.githubusercontent.com/assets/1430576/23067775/1ea0f2c2-f521-11e6-8799-d383245ce6e5.png">

**Comment by possebon** [comment]
I did. After uncomment, I had this screen:

![image](https://cloud.githubusercontent.com/assets/257745/23068259/1b419f8a-f50a-11e6-8811-c573c66a4381.png)

Then after quitting Hyper and loading again, it does not appear anymore, but it's same

![image](https://cloud.githubusercontent.com/assets/257745/23068334/650d640a-f50a-11e6-9759-dc6c8176cad0.png)

How can I check that I'm running the latest version? I checked on index.js inside hyper-plugins/hyper-tab-enhanced, and at least inside the code there is python

**Comment by henrikruscon** [comment]
You're definitely running the old version. It's just iffy sometimes to make sure it updates to the latest. Usually you have to wait for the message that you can restart after forcing an update.

**Comment by possebon** [comment]
I'll uninstall the version using npm then install it again with npm, just to make sure....

**Comment by possebon** [comment]
@henrikdahl finally it's working...

![image](https://cloud.githubusercontent.com/assets/257745/23068783/26deceec-f50c-11e6-8e49-dceecf02c440.png)

I think that it was conflicting with another hyper plugin (hyper-tab-icons). I uninstalled it, then uninstalled the hyper-tabs-enhanced using the npm, just put the hyper-tabs-enhanced on .hyper.js and voilá!

Thanks for your attention.

Best regards,

Fernando Possebon

**Comment by henrikruscon** [comment]
@possebon Not sure what theme you're using but it looks like it's similar to mine.

If you're using mine then it's worth mentioning that I don't override cursorColor, if you comment out the cursorColor in config you'll get the theme colored one instead ✌️

**Comment by possebon** [comment]
Don't wanna bother you, the icon color is not working. Do you think is necessary open a different issue?

 plugins: [
  'hyper-chesterish',
  'hyper-tabs-enhanced',
  'hyper-statusline',
  'hyper-dark-scrollbar',
  'hyper-fileio',
  ],

  hyperTabs: {
      tabIconsColored: true,
      border: true,
      tabIcons: true,
    },

    hyperStatusLine: {
      dirtyColor: 'salmon',
      arrowsColor: 'ivory',
    },

**Comment by henrikruscon** [comment]
Do you mean the tab icons colored?

<img width="697" alt="skarmavbild 2017-02-17 kl 15 47 42" src="https://cloud.githubusercontent.com/assets/1430576/23069624/733be218-f528-11e6-9f3e-3d126208aff3.png">

Is `hyperTabs: {}` inside the `config: {}`? It shouldn't be outside of it next to plugins.

Would probably be ideal if you send your whole config so I can see if anything is wrong.

**Comment by possebon** [comment]
Ok, this is the whole config:

[https://gist.github.com/possebon/465c56ada6b89560c05b8ce14cad4cc4](url)

**Comment by possebon** [comment]
Do you macOS too? In my case vim does not change the icon.

![image](https://cloud.githubusercontent.com/assets/257745/23070176/5482008a-f511-11e6-824a-0eedd3437e12.png)

**Comment by henrikruscon** [comment]
Use this as your config instead, I fixed the formatting for you https://gist.github.com/henrikdahl/1a8e3da772c8c450a1d9c809c4ceff47

**Comment by possebon** [comment]
@henrikdahl you're the man! Colors working!

So I checked the differences, the settings are defined before loading the plugins, correct? This is the only change you did?

**Comment by henrikruscon** [comment]
Is the title `vim .hyper.js` or `vim.hyper.js`?

The settings are defined within the config brackets instead of outside.

**Comment by possebon** [comment]
I change to another file, 

![image](https://cloud.githubusercontent.com/assets/257745/23070525/75cb169a-f512-11e6-973b-e9b5ea150325.png)

**Comment by henrikruscon** [comment]
If you just type `vim` without specifying a file, does it show the icon then? Might be an issue with my RegEx.

**Comment by possebon** [comment]
Yes, without specifying a file, works.

![image](https://cloud.githubusercontent.com/assets/257745/23076990/c6e33924-f529-11e6-8918-68f9bb65749c.png)

**Comment by henrikruscon** [comment]
I'll have to update my regex then, mind sharing your title string with me when you specify a file so that I can test against it?

**Comment by possebon** [comment]
Sure, no problem. I just did vim test.txt on console, on my ~ folder. Is that what you need?

**Comment by henrikruscon** [comment]
Is the title like this `vim test.txt`? With a space between?

**Comment by possebon** [comment]
Yes, that's it. **vim** _space_ **test.txt**

**Comment by henrikruscon** [comment]
@possebon I just published a new version with improved regex matching that should fix your issue ✌️

**Comment by possebon** [comment]
@henrikdahl Great!

![image](https://cloud.githubusercontent.com/assets/257745/23080625/a162c052-f538-11e6-9e51-dc4701dbd39b.png)
